version: "3"
services:
    identidock:
        build:
            context: /e/dev/docker-tools/identidock/
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            ENV: "DEV"
        networks:
            - devko_net
        depends_on:
            - redis
        volumes:
            - /e/dev/docker-tools/identidock/app:/var/src/app

    dnmonster:
        image: amouat/dnmonster
        networks:
            - devko_net
